# TODO put LostTeam text Logo here
---
#Settings for hosting the MySQL server
mysql-settings:
  host: "0.0.0.0"
  port: 3306
  user: "YourUsernameGoesHere"
  password: "YourPasswordGoesHere"
  db: "YourDataBaseNameGoesHere"
...