CREATE TABLE IF NOT EXISTS money(
  id INT(16) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userName VARCHAR(64) UNIQUE KEY NOT NULL,
  cash INT(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS money_mw(
  id INT(16) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userName VARCHAR(64) UNIQUE KEY NOT NULL,
  worldName TEXT NOT NULL,
  cash INT(32) NOT NULL
);